### ISSUE TITLE
Fix border-duplicate-license error issues

### ISSUE THREAD

**Issue by sdegutis** [Atlas-Authority/marketing-automation#104]
- [x] This error is too long for Slack, so it's broken up into multiple messages, which breaks its code-fencing formatting
- [x] The error has pretty-printed objects with unescaped ANSI color codes in it which only makes it harder to read in Slack
- [x] The error itself could be a false positive (again), caused by Atlassian adding new properties that we're not excluding

**Comment by sdegutis** [comment]
I fixed the main aspect of this issue (by removing `status` from identity-fields during checks), but once again it means we're putting off the two other fixes. But they do seem low-priority, so 🤷

**Comment by boris-moduscreate** [comment]
How does this one interact with #118 ?

**Comment by sdegutis** [comment]
It has no interaction, except that #118 makes the Slack error report much easier to read.
