### ISSUE TITLE
Support multiple vendors

### ISSUE THREAD

**Issue by bberenberg** [Atlas-Authority/marketing-automation#107]
If a company has multiple Atlassian Vendor accounts, they may need to run this across those accounts. 

In terms of config, I think it's allowing `MPAC_SELLER_ID` to be comma delimited like so `MPAC_SELLER_ID=1234567,4567890` and then we loop over this.

**Comment by sdegutis** [comment]
During each run, the data from all vendors should be combined and used as if it was from a single vendor, right?

**Comment by bberenberg** [comment]
Yeah that is probably best.

**Comment by sdegutis** [comment]
Hmm each seller account probably has its own email and API key, right? If so, `MPAC_USER` and `MPAC_API_KEY` also need to be comma-separated.

**Comment by bberenberg** [comment]
It could be, but not necessarily. A single user can access both. I don't think we need this in the scope of this ticket. Maybe file a backlog improvement for it.

**Comment by sdegutis** [comment]
Added in #108. Didn't file an issue for the other feature since nobody currently requested or needs it.
