### ISSUE TITLE
Support SEN deprecation

### ISSUE THREAD

**Issue by sdegutis** [Atlas-Authority/marketing-automation#121]
- [x] Update code that assumes unique IDs within a record, as `addonLicenseId` and `appEntitlementNumber` will often be equal
- [x] The code already works when `addonLicenseId` is absent (and doesn't use `hostLicenseId`)
- [x] Update the code to work when `licenseId` is absent

**Comment by boris-moduscreate** [comment]
Can you estimate the amount of hours to complete?

**Comment by sdegutis** [comment]
About an hour.

**Comment by sdegutis** [comment]
Tech notes:

- [ ] The class `MpacStructurer` should be updated to assume license IDs within a record are no longer unique
- [ ] Tests should be written to run the engine on fake licenses that have all fields absent and duplicate new-IDs
