### ISSUE TITLE
Drop support for Multiple in Deployment field

### ISSUE THREAD

**Issue by boris-moduscreate** [Atlas-Authority/marketing-automation#123]
https://github.com/Atlas-Authority/marketing-automation/blob/78ad69ac099b968d8ec9f0950ff0af175a0dad15/src/lib/contact-generator/update-contacts.ts#L48

Having a "multiple" value in HubSpot makes usage of the property complex. We likely want to be additive in checkboxes or something. We regenerate this on every run right? If so, can we purely add the relevant checkboxes?

Note for boris:
This field will be called "License Platform" in the Modus Hubspot.

**Comment by boris-moduscreate** [comment]
@sdegutis can you estimate the volume of work here?

**Comment by sdegutis** [comment]
@boris-moduscreate I'd guess probably an hour optimistically, 3 to be safe.

**Comment by boris-moduscreate** [comment]
Does this backfill past data in a sane way? I think we need associated docs for this change?

**Comment by sdegutis** [comment]
Yeah it backfills properly. It also updates all relevant docs including changelog entry.

**Comment by sdegutis** [comment]
You can see the .md files changed in https://github.com/Atlas-Authority/marketing-automation/pull/124/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
