### ISSUE TITLE
Add ability to post to Slack via URL

### ISSUE THREAD

**Issue by sdegutis** [Atlas-Authority/marketing-automation#127]
For example:

```sh
$ curl \
   -X POST \
   -H 'Content-type: application/json' \
   --data '{"text":"Hello, World!"}' \
   https://hooks.slack.com/services/[some-code]/[another-code]/[yet-another-code-but-longer-this-time]
```

One thing to consider: can this URL be used for both `chat:write` and `files:write` scope? Or does it need two separate URLs?

**Comment by boris-moduscreate** [comment]
@sdegutis does this still need to happen or can we close this? I thought we already did something related to this?
