### ISSUE TITLE
Move authentication to use a private app

### ISSUE THREAD

**Issue by boris-moduscreate** [Atlas-Authority/marketing-automation#130]
Why? 

- https://developers.hubspot.com/changelog/upcoming-api-key-sunset
- https://community.hubspot.com/t5/Developer-Announcements/Upcoming-API-Key-Sunset/m-p/642739

Resources:

- https://developers.hubspot.com/docs/api/private-apps
- https://developers.hubspot.com/docs/api/migrate-an-api-key-integration-to-a-private-app

**Comment by sdegutis** [comment]
Looks like we did this already in #53 for #48. I can send a PR that officially removes API key support if you want.

**Comment by sdegutis** [comment]
Sent PR https://github.com/Atlas-Authority/marketing-automation/pull/134
