### ISSUE TITLE
Handle new HubSpot custom association types

### ISSUE THREAD

**Issue by sdegutis** [Atlas-Authority/marketing-automation#142]
For example, you may have a new HubSpot association type of "Contractor" which is a special association type from company to contact.

Previously, this project assumed the API would always return an association type in the format `{type1}_to_{type2)`. This allowed us to map the entities within the engine's internal data structures. So we would internally parse this string to get `{ from: type1, to: type2 }`

However, if the HubSpot account has a new custom association like "Contractor", the API will now return "contractor" for that association instead. This means we need to map that to our internal association format `{ from: type1, to: type2 }`, but the information is only implied, and we need to provide it explicitly to the engine somehow.

I see two options for this:

1. Just hardcode it and be done with it.
2. Add an ENV variable that maps the new name to the old type.

The first way is not very flexible, but works well if (a) we don't create a lot of custom association types, and (b) everyone using this engine pretty much always has the same custom association types with the same names.

If we go the second way, I would recommend we'd use a comma-separated format that just reuses the format HubSpot already (still) uses, like `HUBSPOT_ASSOCIATION_TYPE_MAPPINGS=contractor:company_to_contact,some_other_type:contact_to_deal`.

**Comment by sdegutis** [comment]
I thought a third option might be to use the new [v4 API](https://developers.hubspot.com/docs/api/crm/associations) to automatically figure out this mapping, but `/crm/v4/associations/{fromObjectType}/{toObjectType}/labels` is the only endpoint that might give us what we'd need for that, but it only tells us the name (which we already know), and whether it's user-defined or HubSpot-defined, which doesn't help us. It also gives us a `typeId`, but I can't find any endpoints that map that to from/to types. So that seems off the table for now.

**Comment by boris-moduscreate** [comment]
Ok so lets do 2. 

Btw, you need to tag me in an issue for me to get notified. I had no idea this issue existed.

**Comment by sdegutis** [comment]
Ok will do, to both parts.

**Comment by boris-moduscreate** [comment]
@sdegutis can we close this? Can we also expand docs a bit to explain what the env variable mappings should be? It's not obvious how this should be used now?

**Comment by sdegutis** [comment]
@boris-moduscreate The docs for HUBSPOT_ASSOCIATION_TYPE_MAPPINGS should probably be the same, the only difference is that it shouldn't matter which order you put them in now. But it was always confusing to figure out the order in the first place, so in practice it was kind of guesswork, and that doesn't change with this PR, it just means the user will have success slightly sooner.

**Comment by boris-moduscreate** [comment]
I don't understand why you closed this. My ask is that we build out docs here before closing this. Current docs aren't sufficient/

**Comment by sdegutis** [comment]
I thought you meant the docs in .sample.env which describe the format of HUBSPOT_ASSOCIATION_TYPE_MAPPINGS, but I'll add docs for this ENV variable to HUBSPOT.md also.

**Comment by sdegutis** [comment]
Would this be sufficient to add to hubspot.md?

---

## Custom Association Types

HubSpot allows custom association types, for example, a Partner can be an association between a Company and a Contact.

This project supports custom association types via the ENV variable `HUBSPOT_ASSOCIATION_TYPE_MAPPINGS` which must be in the comma-separated format `partner=company_to_contact,[...]`. The order of entity types within each mapping does not matter, so `partner=contact_to_company` would be equivalent.

**Comment by boris-moduscreate** [comment]
Sure, but we need to call out where those IDs come from, and provide examples, etc

**Comment by sdegutis** [comment]
Okay this is my idea for a cleaned up and fleshed out version:

---


## Custom Association Types

HubSpot allows custom association types, for example, a Partner can be an association between a Company and a Contact.

This project supports custom association types via an ENV variable, using the following format derivation rules:

* The ENV variable is `HUBSPOT_ASSOCIATION_TYPE_MAPPINGS`
* The format must be `partner=company_to_contact,[...]`
* The format allows for multiple comma-separated mappings
* The LHS of each mapping (e.g. `partner`) is derived via:
  * Take the name of the custom association, e.g. `Board Member`
  * Lower-case it, e.g. `board member`
  * Replace spaces with underscores, e.g. `board_member`
* The RHS of each mapping (e.g. `company_to_contact`) is derived via:
  * Take the names of both entity types in the association (e.g. `Contact` and `Company`)
  * Apply the same rules as the LHS above (e.g. `contact` and `company`)
  * Join them with the string `_to_` (e.g. `contact_to_company`)
  * Note: the order does not matter in this mapping (e.g. `company_to_contact` is equivalent to the above)

**Comment by boris-moduscreate** [comment]
I tweaked the copy a bit but yes thats fine.

**Comment by sdegutis** [comment]
Just pushed these docs on the `main` branch, since they're implicitly approved by you. Since they were the only thing left that you requested for this task, I think we can close this issue.
