### ISSUE TITLE
Handle upcoming MPAC data changes

### ISSUE THREAD

**Issue by sdegutis** [Atlas-Authority/marketing-automation#145]
Based on https://community.developer.atlassian.com/t/update-on-addressing-issues-with-marketplace-reporting-and-apis-general-availability-begins-this-week/62465

The bulk of incoming data changes will likely only result in noisy one-time data shift reports. After that, the data will basically just be more accurate, and that's pretty much it. It's possible that it may also give us more information that will help us resolve #118, but that's unclear at this point.

However, one change raises a question about our current engine logic:

> Transactions show point in time (when the transaction was created) contact details whereas licenses show latest contact details. This means that contact details for license need not be in sync with latest invoices transactions contact details if contact is updated post last renewal.

When merging contact data for the same contact found in different records in MPAC data, the engine already sorts by the `lastUpdated` that this paragraph is referring to. However, it also digs deeper into the older versions of a contact in order to avoid having empty information. For example, if the latest version does not have first and last name, it looks for an older version of that contact that does have both first and last name, and uses that pair of first/last name in the HubSpot contact. Although I believe this was the correct logic at the time that part of the engine was written, we may want to just delete the first/last name from the HubSpot Contact if the latest MPAC contact now omits it.

**Comment by sdegutis** [comment]
Pinging @boris-moduscreate

**Comment by boris-moduscreate** [comment]
Not sure I understand the last point. Why would we have a nameless contact if we have historical information that we can use?

**Comment by sdegutis** [comment]
A better example might be city/state. They may have moved, and going from having an existing-but-incorrect location to no-location might be the right solution.

But even with first/last name, they might have changed name (e.g. got married and changed last name). In this case, I think it's still valid to keep the outdated name.

The full logic that we use:

```
Use latest first/last name pair
If no pair is found
  Use latest first-name
  Use latest last-name

Use latest city/state pair
If no pair is found
  Use latest city
  Use latest state

Use latest phone
```

**Comment by boris-moduscreate** [comment]
Updating  to a value makes sense. Updating to empty doesn't. I think our current logic is correct.

**Comment by sdegutis** [comment]
Then I think we can close this as basically nothing-to-do.

**Comment by boris-moduscreate** [comment]
@sdegutis do we have a way to run the data shift report without performing a push to Hubspot?

**Comment by sdegutis** [comment]
@boris-moduscreate Nope, each engine run starts with data shift analysis. We could add a little web UI that allows us to manually request a data shift report or manually run the engine, but other than that I don't see any way we could interact with the Node process.

**Comment by boris-moduscreate** [comment]
Can we break upload to hubspot in some way? Or for example could we do a local run on your system, then change source URLs based on whats posted at https://community.developer.atlassian.com/t/update-on-addressing-issues-with-marketplace-reporting-and-apis-general-availability-begins-this-week/62465/14 and see what the data shift report throws?

**Comment by sdegutis** [comment]
Yep, I'll do that now.

**Comment by sdegutis** [comment]
Just ran the report locally on data from regular endpoints and preview endpoints and sent it in an email.

**Comment by boris-moduscreate** [comment]
For the sake of non-modus people reading this. Our internal test showed that amounts on some transactions got trimmed to a sane number of cents rather than 3+ numbers after the decimal point. We also found that a number of licenses and transactions disappeared and reported this to the appropriate team. At this time, it looks like this codebase is fine to use with the new data pipeline.
