### ISSUE TITLE
Question: How to distinguish between CLOSED_WON and closed renewal?

### ISSUE THREAD

**Issue by ukuhnhardt** [Atlas-Authority/marketing-automation#147]
In Hubspot we have a deal stage property 'closed won renewal'
<img width="855" alt="image" src="https://user-images.githubusercontent.com/2417004/200709102-420cf925-154c-4c91-bdcc-4de182f53f05.png">

I think this is the natural progression from 'closed won' of the initial eval conversion.

MP data actually specifies sale type as 'renewal'.

I would like to explore how the automation can facilitate that new deal stage.

**Comment by boris-moduscreate** [comment]
I would say use HubSpot automation based on it moving into Closed Won and Sale Type being Renewal? I don't think we want to support this level of customization within the automation code itself. Let me know if you disagree.

**Comment by boris-moduscreate** [comment]
Closing this out for now.
