### ISSUE TITLE
Add support for Cloud Identifiers that will replace SEN numbers

### ISSUE THREAD

**Issue by bberenberg** [Atlas-Authority/marketing-automation#16]
Please review https://community.developer.atlassian.com/t/introduction-of-new-install-payload-fields-as-part-of-sen-replacement/50029 and associated links to estimate how much work it will be to add support for this. Then we will schedule the work.

**Comment by sdegutis** [comment]
Some notes for later:

- Deals have `addonLicenseId` and `trasactionId` separately
- When these IDs land, we'll probably need to add `entitlementNumber` and entitlementId`
- We'll probably want to do a quick data-analyzation to verify assumptions about uniqueness characteristics of these IDs
- We'll probably want to add a phase early in the code that verifies known characteristics about ID uniqueness

**Comment by sdegutis** [comment]
@bberenberg Ok I think we have enough info now to estimate work for this. So, assuming:

- All licenses continue to have `addonLicenseId` for a little while longer
- Some (all?) licenses have `entitlementNumber` and `entitlementId`
- Some (all?) transactions have `entitlementNumber` and `entitlmentId`

Then I think the tasks here would be:

- [ ] Verify new IDs actually map transactions to licenses correctly
- [ ] Add 2 new fields to Deals via HubSpot UI
- [ ] Add these 2 new fields to ENV variable
- [ ] Update deal-generator to lookup deals by new IDs before SEN
- [ ] Do a few dry-runs and see what happens

Due to recent engine improvements, overall I think this should take no more than a few hours.

**Comment by bberenberg** [comment]
Right, let's delay till Dec 15th when this data is live for us to play with.

**Comment by sdegutis** [comment]
Ok so after looking at the data, it looks like the above plan is still good, and it should take about a day.

**Comment by sdegutis** [comment]
Should MAE try to look up deals in HubSpot using both numbers, just in case one is missing? I get that Entitlement IDs/Numbers will be a replacement for SENs, but, having two new numbers that are both supposed to always be present for Cloud apps, I'm honestly not sure what MAE should do here.

**Comment by sdegutis** [comment]
Ok yeah I'm just gonna code it to look deals up by both anyway. It makes no sense, but we have two IDs so I'll use both.

**Comment by bberenberg** [comment]
Why not all three? :p

**Comment by sdegutis** [comment]
Ok I have a good plan for the second half of this task.

The main places MAE assumes there's an `addonLicenseId` is:

- [ ] When connecting licenses and their transactions at the beginning of engine run
- [ ] When matching up licenses by contact/company data similarity
- [x] When looking up deals in HubSpot by MPAC idents (done)
- [ ] When updating HubSpot ident fields when we have more info
- [ ] In all our logs, where we always assumed this is the main unique ident

To fix all of these, we mainly have to:

- [ ] Update the matching in the early phase to check via 3 IDs in case one's missing
- [ ] Update the logs

**Comment by sdegutis** [comment]
The one issue is that we cache to disk the license-matching score results, which currently use `addonLicenseId`. This process could take several minutes, and hinders development, so when MPAC data hasn't changed during dev (e.g. you haven't redownloaded it), it's fine to cache this to drastically speed up dev.

To keep this cache file working for the dev speedup when `addonLicenseId` might be missing on a license, we would need to store both the ID itself, and the kind of ID (SEN, AEI, or AEN) in the file.

But honestly this cache file has always seemed like the wrong solution. Maybe now after developing this for some time, we can come up with some logical shortcuts to speed up the scoring engine. This would be ideal, but isn't likely.

**Comment by sdegutis** [comment]
Mostly solved the score-caching issue by cutting the scoring time down to about 25% of what it was, which is now reasonably small enough to go without a score-cache file during dev.

**Comment by bberenberg** [comment]
How did we cut 75% of the time? I know we had intentionally made it inefficient in the past in order to retain scoring accuracy.

**Comment by sdegutis** [comment]
We haven't had an opportunity to touch this part of the code in a year, and I was a much worse dev back then. As soon as I looked at this code again two days ago, I saw some opportunities to speed it up. Specifically, when we compare two licenses to see if they're the same:

1. When the score is already over the threshold, we bail with yes
2. When the score is so low that winning all potential remaining scores can't hit the threshold, we bail with no
3. I modified a third-party library we were using for string similarity to take out cases we don't use

**Comment by sdegutis** [comment]
The only downside is that we now have to spend a little time (maybe an hour or two) updating the score-logging, which is useful for anyone who needs to tweak the algorithm but not useful during general engine runs.

**Comment by sdegutis** [comment]
Here's what's left:

* [ ]  Add both fields in HubSpot and add their field idents to ENV
* [ ]  Wait for guidance on what to do about `evaluationLicense` field ([CDAC thread](https://community.developer.atlassian.com/t/upcoming-changes-in-marketplace-to-support-sen-replacement/53022/31?u=steven))

After those are done, we can close this out.

**Comment by sdegutis** [comment]
They got back to us, saying that sometimes it will be `addonLicenseId` (as it now always is), and sometimes `appEntitlementId`. So we have one last task:

- [ ] Map eval license by `addonLicenseId` or `appEntitlementId`

**Comment by boris-moduscreate** [comment]
@sdegutis can you please review https://atlassianpartners.atlassian.net/wiki/spaces/resources/pages/209977741/Resources+for+Marketplace+Partners+to+navigate+changes+to+Atlassian+s+billing+system#Appendix-A%3A-Reporting-API-Changes and confirm that we don't need to do anything new? For example, will we be able to handle the data when the old fields are removed? If there is anything new we need to do, please file appropriate issues for those and link them here.

**Comment by sdegutis** [comment]
@boris-moduscreate neither of my work emails have permission to view that page, can you add me somehow?

**Comment by sdegutis** [comment]
Created #121 to track this.
