### ISSUE TITLE
Make sure Customer is first contact, and Partner is last

### ISSUE THREAD

**Issue by sdegutis** [Atlas-Authority/marketing-automation#17]
Might need to tweak order that contacts are associated with a deal when associating them, so that Customers are all before Partners.

**Comment by sdegutis** [comment]
The order of contact associations for a deal when retrieved via the API does not seem to match up to the order of these same contacts for a deal in Hubspot's web UI.

Looking further into it strongly indicates the order is kind of random: https://community.hubspot.com/t5/APIs-Integrations/Deals-API-Order-of-Associations/td-p/326540

Just tried to use the API to undo an association of 2 contacts to a specific deal and then re-associate them in order. No matter which order put both contacts, they show up in the same order in Hubspot.

I also tried to make the re-associations be in 2 separate API calls, still same result: no different in contact order in Hubspot web UI for that deal.

So I think this *might* not be possible currently.

**Comment by bberenberg** [comment]
Can we ensure we add them in the order of customer then others when we're making the deals and call it done?

**Comment by sdegutis** [comment]
Will do.

**Comment by sdegutis** [comment]
Done.

**Comment by bberenberg** [comment]
PR?

**Comment by sdegutis** [comment]
Yep, this and #18 are on main. Still working on #19.
