### ISSUE TITLE
Make use of new eval-data keys

### ISSUE THREAD

**Issue by sdegutis** [Atlas-Authority/marketing-automation#24]
New keys exist on some licenses:

```ts
interface NewKeys {
  evaluationLicense:   string, // same format as `addonLicenseId` and often the same within a license
  daysToConvertEval:   string, // always a number in string form parsable with +n
  evaluationStartDate: string, // always 2022-02-22 format
  evaluationEndDate:   string, // always 2022-02-22 format
  evaluationSaleDate:  string, // always 2022-02-22 format
}
```

**Comment by sdegutis** [comment]
All the ways I can think of how we can use this data so far:

1. We can use this to link an eval to a purchase in the license matcher with 100% certainty
2. When linking an eval to a purchase, we can skip the 90-day gap check, since we already have 100% certainty
3. ???

Can't think of any uses yet for the 3 dates. (`evaluationSaleDate - evaluationEndDate` is already how `daysToConvertEval` is calculated by Atlassian.)

**Comment by bberenberg** [comment]
Yeah makes sense, can we add this to increase data confidence?

**Comment by sdegutis** [comment]
👍 it should help, working on it now.

**Comment by sdegutis** [comment]
Some considerations before merging #47. When connecting licenses (via new `evaluationLicense` key) that matcher hasn't already connected, the main change is that deals that are closed-lost and >90 days away from a closed-won, are going to be connected, and the closed-lost will be considered a dup of the closed-won by the engine. Without merging this PR, we'll just see fewer warnings about dups. This PR also won't/can't prevent the closed-lost from being created, because it could be months into the future when a purchase occurs that is connected to that closed-lost via the eval-license key.

**Comment by sdegutis** [comment]
Some more considerations:

1. If new eval-keys are only available for e.g. 1% of total licenses, there are inevitably not going to be many new connections. But over time, as this number increases, there will be more connections made, which should help fill in gaps in the scoring engine.

2. As more licenses are connected, more contacts are connected, which will give a stronger indication for matching contacts/companies to deals, and which contacts to flag as partners.

3. To deal with the fact that this will inevitably consider past closed-lost evals as dups of new closed-wons, we can have isolated code that deletes those dups **iff** it's closed-lost, $0, and has no manual user activity (notes, emails, meetings, etc). This would be the first and only spot in the codebase that deletes anything from HubSpot, and it would be very thoroughly tested and guarded from bugs/errors.

**Comment by sdegutis** [comment]
For point 3, alternatively we could just ignore those closed-lost deals from the engine and not print them in the dup-deals report. Has the same effect but leaves them in HS and doesn't require us to write any HubSpot-entity-deleting code.

**Comment by bberenberg** [comment]
My idea would be to have an option controlled by two ENV variable. One for how do you handle duplicate issues. The other for how you handle deletions in general.

Name HUBSPOT_DUPLICATE
Options are:

- none
- log (default)
- delete

Options are comma separated and can be stacked. If none is combined with others, then it's a noop and overrides the other options.

Name: HUBSPOT_DELETE

Options are:
- none (default) - prevent deletions
- log - log intended deletions
- delete - perform the actual deletion
- slack - notify slack of an intended deletion

Options are comma separated and can be stacked. If none is combined with others, then it's a noop and overrides the other options.

Intent here is that we would roll this out with only `log,slack` initially, see what comes up, then if it's sane, we can enable the delete flag. We can also enable the delete flag for a single restart when we want to run a cleanup of some kind of data.

**Comment by sdegutis** [comment]
This sounds like a good idea, but I wonder about the fact that it has the same options duplicated between the two actions, just at different levels. I think we could probably combine them, since the only time we'll probably ever want to delete any HS data is when it's a closed-lost and $0 duplicate deal. I can't imagine any other time we'd want to delete.

**Comment by sdegutis** [comment]
Also, I think this might be a good use-case for a web UI. So that the web UI can show the most recent run's result data, making it filterable, searchable, etc. and also providing buttons for various actions. The only ones right now would be to delete duplicate deals.

**Comment by sdegutis** [comment]
I think [this comment](https://github.com/Atlas-Authority/marketing-automation/issues/24#issuecomment-972112040) was wrong, where I thought we can't prevent duplicate deals even when we can match them via eval keys.

My reasoning was that, if a future engine run now sees that two created deals are related via the new MPAC key, it's too late to connect them.

But I forgot to consider: the license matcher runs *before* the deal creation phase. So it won't even *create* the second one, once it sees that the deal already has a closed-lost deal from a past inactive eval.

Which means, while that will reveal more duplicates created *before* this change (by connecting more deals via connecting more licenses), it should actually prevent *new* duplicates from being created.

So overall I think we should merge #47, then see if the number of duplicates grows over time. If I'm right, it shouldn't. In which case, duplicates will be a one-time thing to deal with. Which would make dealing with them manually (even if automated) a better solution than a long-term feature.

**Comment by bberenberg** [comment]
Works for me.
