### ISSUE TITLE
Agree on how we collaborate

### ISSUE THREAD

**Issue by bberenberg** [Atlas-Authority/marketing-automation#34]
- Change-logs?
- Who approves PRs?
  - My preference is that Atlas Authority remain BDFL (for the foreseeable future)
- How do we do versioning? Strict [SEMVER](https://semver.org/)?

Any other questions we need to answer?

Items not up for debate within the scope of this ticket:

- repo will be primarily tracked on GH and associated tools
  - Issues will be tracked in GH
  - Docs / etc should be in markdown alongside relevant code / etc
  - CI/CD will remain in GH Actions
  - Bundling will remain as a docker image (you can add other destinations, but don't remove this one)

**Comment by sdegutis** [comment]
My 2¢: CalVer makes more sense than SemVer, as it adds meaning to the version numbers, that allow us to quickly look at (and reproduce if needed) whatever external data and APIs looked like at the time of that version. So we could use 21.11.3 to mean the third change during 2021-11 (this month). This plus a little high-level changelog for each version I think would probably be enough for most use-cases I can imagine but can only vaguely remember right now.

**Comment by ramblingenzyme** [comment]
As a third party consuming this, I'd prefer SemVer to know what to expect when syncing our fork, i.e. if we'd need to make changes to how it's run or configured or big behavioral changes to the data generated. We can always figure out when a version was released based on the git history.

**Comment by sdegutis** [comment]
I'd agree, semver makes more sense, so you know how big of a compatibility change there is for each version.

**Comment by bberenberg** [comment]
Outcomes:

- Change Logs will be a thing
- SemVer will be used for versioning
- Atlas Authority will be BDFL for now and approve PRs

If people want to re-open these conversations, please file a new issue.
