### ISSUE TITLE
Running with cached downloader or console uploader first time fails without data directory

### ISSUE THREAD

**Issue by ramblingenzyme** [Atlas-Authority/marketing-automation#35]
* The MemoryRemote class expects the files in the data/in directory to exist, since it's used as the uploader too, it still expects the files to exist.

Expected behaviour:
* Running `run-once.ts -- --downloader=cached --uploader=console` without a cache should succeed and create the required files

**Comment by sdegutis** [comment]
So dry-running with local input and output when there’s no cached data files would just create empty arrays as local cache files, run on this empty data set, and produce essentially no updates? Is that the expected behavior in this issue? I always just run “npm run download” before using —in=local so I have real data cached to work with.

**Comment by ramblingenzyme** [comment]
Seems to be fixed now. The issue was actually with running `run-once.ts -- --downloader=live --uploader=console` after you check out, it was throwing without the `data/in` directory. We haven't synced yet, but checking out your main branch this morning and using the new --in/--out arguments it seems to be fixed.
![image](https://user-images.githubusercontent.com/5336472/140424641-66b7ea33-fc85-4880-8e25-7bc57cc64ab0.png)
![image](https://user-images.githubusercontent.com/5336472/140424693-b23e32e0-c1b5-4765-b93d-1d186c2310b3.png)

First run in our fork, second from your main branch. Both cloned from scratch, then my .env from my dev copy copied in.

**Comment by sdegutis** [comment]
Ah yeah, the branch also fixed a crash specific to `--downloader=live --uploader=console` (started in 8fc5d6e7ccb05f109e770744ea701debebe0a616 and finished in 28ca0026cb0226ee49c8685e614806aab3be03c7). Not sure if this is what you ran into, but glad it's resolved for you in any case.
