### ISSUE TITLE
No documentation about expected custom properties

### ISSUE THREAD

**Issue by ramblingenzyme** [Atlas-Authority/marketing-automation#36]
On contacts, on top of the properties in .sample.env we had to create:
* contact_type
* region
* related_products
* license_tier
* last_mpac_event

For deals:
* related_products

**Comment by ea-jamiebousfield** [comment]
In addition we had to create these fields for deals:
- Related Products (related_products) --- mentioned above
- License Tier (license_tier)
- Country (country)
- Origin (origin)

**Comment by bberenberg** [comment]
@sdegutis Are these ones we haven't moved into ENV variables yet?

**Comment by sdegutis** [comment]
Yep, we have to move these into ENV variables and document them in the README as needing to be created in HubSpot.

**Comment by bberenberg** [comment]
Let's make sure we only make them required if we actually need them for processing, otherwise optional.

Also, let's make sure we document HS field types:
<img width="503" alt="Property settings - Screenshot 2021-11-02 at 19 01 57" src="https://user-images.githubusercontent.com/4259775/140320024-080a7595-b252-4176-b067-7700e570feab.png">
<img width="603" alt="Property settings - Screenshot 2021-11-02 at 19 02 08" src="https://user-images.githubusercontent.com/4259775/140320027-7c8d9301-a076-4092-8a75-7ce7d6d9d3a8.png">
<img width="483" alt="Property settings - Screenshot 2021-11-02 at 19 01 29" src="https://user-images.githubusercontent.com/4259775/140320028-9c6c5dfc-e5f1-4d92-bf59-bc92c61f5825.png">

**Comment by ramblingenzyme** [comment]
Good point about documenting the data types, that'll be super useful for figuring out how to configure the fields for user friendliness.

For context we created them all as single line text fields and the project still runs, so incorrect data types in Hubspot don't break it.

**Comment by sdegutis** [comment]
Hey all.

Based on everything in this issue, here are the tables I came up with and plan to put in the readme.

Please let me know if you have any questions or comments.


### Contacts

| Field            | Type     | Allowed Values                           | ENV var                           | Required |
| ---------------- | -------- | ---------------------------------------- | --------------------------------- | -------- |
| License Tier     | Number   | *                                        | TBD                               | ❌        |
| Contact Type     | 1-Select | 'Partner' or 'Customer'                  | TBD                               | ❌        |
| Region           | 1-Select | "region" of MPAC records                 | TBD                               | ❌        |
| Related Products | N-Select | `ADDONKEY_PLATFORMS` rhs vals            | TBD                               | ❌        |
| Products         | N-Select | "addonKey" of MPAC records               | `HUBSPOT_CONTACT_PRODUCTS_ATTR`   | ❌        |
| Deployment       | 1-Select | "hosting" of MPAC records, or 'Multiple' | `HUBSPOT_CONTACT_DEPLOYMENT_ATTR` | ❌        |
| Last MPAC Event  | Date     | *                                        | TBD                               | ❌        |

### Deals

| Field            | Type        | Allowed Values             | ENV var                            | Required |
| ---------------- | ----------- | -------------------------- | ---------------------------------- | -------- |
| License Tier     | Number      | *                          | TBD                                | ❌        |
| Related Products | 1-Select    | `DEAL_RELATED_PRODUCTS`    | TBD                                | ❌        |
| Origin           | 1-Select    | `DEAL_ORIGIN`              | TBD                                | ❌        |
| Deployment       | 1-Select    | "hosting" of MPAC records  | `HUBSPOT_DEAL_DEPLOYMENT_ATTR`     | ❌        |
| App              | 1-Select    | "addonKey" of MPAC records | `HUBSPOT_DEAL_APP_ATTR`            | ❌        |
| Country          | 1-line Text | "country" of MPAC records  | TBD                                | ❌        |
| AddonLicenseId   | 1-line Text | (for engine use)           | `HUBSPOT_DEAL_ADDONLICENESID_ATTR` | ✔️        |
| TransactionId    | 1-line Text | (for engine use)           | `HUBSPOT_DEAL_TRANSACTIONID_ATTR`  | ✔️        |

(TBD ENV vars will be filled in as part of the PR that resolves this issue.)
