### ISSUE TITLE
Evaluate switching to HubSpot Private App

### ISSUE THREAD

**Issue by bberenberg** [Atlas-Authority/marketing-automation#48]
Instead of using the global API key, we should look at using https://developers.hubspot.com/docs/api/private-apps

**Comment by sdegutis** [comment]
This is deployed and merged. To start using it:

1. Create the private HS app, and add read/write scopes for contact/deal/company (6 total).
2. Give me `HUBSPOT_ACCESS_TOKEN` token from the private app, and I'll add to ENV and redeploy.

I'll document these steps in the engine docs/readme/something.

**Comment by bberenberg** [comment]
I have created an app with the following scopes:

- crm.objects.contacts.write
- crm.objects.companies.write
- crm.objects.companies.read
- crm.objects.deals.read
- crm.objects.deals.write
- crm.objects.contacts.read

And added `HUBSPOT_ACCESS_TOKEN` to the portainer config, so you should be able to test this out in prod now. I did not remove the API env variable.

**Comment by sdegutis** [comment]
Looks like it ran successfully. And the commit with documentation is pushed. I think we can close this now.

**Comment by bberenberg** [comment]
Will it run with the other API env variable removed?

**Comment by sdegutis** [comment]
Yep. If both are present, it chooses access key. If only one is present, it uses that. If none are present, it logs that you need one and quits.

I can remove the API key now.

**Comment by sdegutis** [comment]
Done, and verified it worked as expected 👍
