### ISSUE TITLE
Data shift monitoring across runs

### ISSUE THREAD

**Issue by sdegutis** [Atlas-Authority/marketing-automation#59]
Current use cases we want to support:

- Old licenses / transactions disappear
- Old licenses / transactions appear past some threshold (let's say more than 30 days old)
- Data in old licenses / transactions changes (For example amount, or something else)

Basically we want to recognize create/update/delete patterns in downstream MPAC data.

Subtasks:

- [x] #79
  - Updated the engine to take configurable input directories
  - Currently, production always uses same dir, dev tasks use timestamped dirs
  - Production now writes to disk first, then feeds that into the engine
- [x] #80
  - We'll need a way for the next task to know which data set is the latest to run on
  - We'll need a way for the next task to delete data sets that it determines are stale
  - This will have to keep a record in a metadata file on each download and engine run
- [x] #81
  - It will parse user-configuration (via ENV)
  - It will delete data sets past a certain retention threshold
  - Its logic probably should be thoroughly tested with unit tests
- [x] #82
  - Now that we have managed backups, we can analyze their data
  - Analyzing data sets over time will happen just before each engine run
  - We may need a bit of Slack configuration unless we want to reuse error-reporting configs

**Comment by sdegutis** [comment]
I think this means we'll need to save at least some data from each run, for future runs.

What data we specifically save, depends on what we want to do:

1. If we just want to report to Slack that a transaction went missing from input APIs, we only need the transaction number, or whatever it is we need for reporting.

2. But if we want to preserve missing transactions/licenses and pipe them through the engine as if they came back normally from the API, we'll need to save everything at every run.

Some considerations for either route:

1. We'll still have to redownload everything at each run to update the database.
2. It won't be a big code change, since we already cache to disk to speed up dev-mode.
3. Production will just need a new persistent volume for the Docker image.

**Comment by sdegutis** [comment]
Adding some notes from discussion:

This should keep multiple copies over time.
It should use a backoff retention schedule.
This should be ENV-configurable.

So, for example, you might want:

- Keep daily backups for - 8 days
- Keep weekly backups for - 5 weeks
- Keep monthly backups for - 2 Months

In this example, you'd have 15 backups at any time, going back 2 months.

**Comment by sdegutis** [comment]
@bberenberg  I plan to make this ENV configurable using this syntax:

    BACKUP_SCHEDULE="d8d w5w m2m"

This is shorthand for "daily for 8 days" etc., which are AND'd together.

This way you can specify "d2m" to keep the past 30 days, and "d2m w6m" to keep daily past 30 days + weekly past 6 months.

These would all look at the Node.js's local time and consider midnight the beginning of a day, and the first run after midnight (or the first run when started?) as the first run of that day, etc. for each unit of time.

**Comment by sdegutis** [comment]
"d2w" would be "daily for 2 weeks" which is once a day for 14 days. I mean the syntax isn't hard, it's maybe 30 lines of code and should take 20 minutes to write, and it makes it super flexible. My only concern is, because I chose one so quick and easy for me to code up, it's maybe hard for humans to read/write? But that's up to you.

**Comment by bberenberg** [comment]
I am less worried about parsing the syntax, and more so creating a reliable implementation of arbitrary retention. Backup companies spend years ironing out edge cases.

**Comment by sdegutis** [comment]
I just started on the phase of thinking up an overall concrete implementation plan. After I do a write-up, we can more easily pinpoint pain points and discuss/resolve them.

**Comment by sdegutis** [comment]
Ok got it:

## The Backup aspect

This section is about backups, because we need to keep the backups in order to calculate data drift over time. The next section is about data-drift.

### What can users configure?

You can configure multiple schedules which all run at the same time.

For example:

* Daily for 2 weeks
* Weekly for 4 weeks
* Monthly for 6 months

This would eventually give you 14 + 4 + 6 = 24 backups spread out over 6 months.

### How would this work in production?

Each run will always download new MPAC data. If another backup is needed by any configured schedules, we write this new MPAC to a new backup dir.

### How do we test it during dev?

We'd test the function that checks whether another backup is needed.

For its input, it takes previous backup dates/times, and the current date/time.

Its output is just a yes or no.

We can write way tons of tests here to get super confidence.

### Where are they stored?

We'd store all the backups in a persistent Docker volume in production.

The GCF unit of time of each possible configuration will be the lowest unit of date/time we store in the directory name, and will parse that to know when it was made.

I'm proposing we don't go lower than a day for the GCF, since runtimes themselves are also configurable (at the level of hours/minutes/seconds).

Each dir will only store licenes/transactions.

### What happens if you restart Docker?

This shouldn't matter. The previous backups dates/times are stored along with the backups themselves, so we just continue where we left off as if Docker never restarted.

### But what about the fact that it might run twice in a row?

Still doesn't matter. The schedule is the schedule, we just go by that. If the `shouldBackup(pastBackupDateTimes, currentDateTime)` says we shouldn't backup now, it's not going to give a different answer in 10 minutes.

### What happens if you change the ENV schedule between restarts?

It should just work, because it'll look at the old backup dates/times to know whether to backup again or not, at the current run and all future runs.

## The data-drift aspect

What we do here depends on the scope you want to accomplish with this issue.

So far, the ideas I have are:

1. We can notice when data goes missing from licenses/transactions, and fill in the gaps with backups
2. We can notice when licenses/transactions themselves go missing, and fill them in too
3. We can log this to get an idea of MPAC data flux patterns
4. We can notice when data gets changed and act on it---but TBH that's going to happen a ton, I predict, so I'm not sure this is helpful.
5. ???

What do you think

**Comment by sdegutis** [comment]
And maybe these are two separate issues: Backup and Data-drift, where Data-drift depends on Backups being done, but Backups are independently useful? Dunno...

**Comment by sdegutis** [comment]
Got a few more updates:

* The main purpose of this is for notification.
* And the main output of notification is Slack.
* The main thing we want to notify about is created/updated/deleted.

See the original issue description for more details.

**Comment by sdegutis** [comment]
Reducing flexibility of backup schedule (initial idea above was based on my misunderstanding).
Now it's `KEEP_DATA_SETS=8d 5w 2m` (ENV var), where d=days, w=weeks, m=months.
So you could read this one as as "keep data sets for 8 days, 5 weeks, and 2 months."

**Comment by sdegutis** [comment]
Since I wasn't sure how long this task would take, I had the following plan:

1. Split it into 4 smaller tasks
2. Do a PR for each task
3. Make sure each PR is a fully functioning system

* The first task took the longest so far, being about a week, and has been merged.
* The middle two tasks were each half a day (yesterday), and PRs are waiting for review.
* The last and current task may take up to a few days by my current estimate.

**Comment by sdegutis** [comment]
The fact that there's 1 of 3 IDs on any given MPAC record, potentially complicates identifying them across data sets. Trying to think of a basic way to say "this is the same license as that one from the week before, even though this as ID1=a and that has ID2=b and both only have the one ID". If we can assume data doesn't change, then we could just compare a subset of the data. But the data in it might also change too. But maybe not all of it...

**Comment by sdegutis** [comment]
Actually that's not an issue, since Atlassian is gradually phasing out the one ID and keeping both new and old IDs side by side for a while.

**Comment by sdegutis** [comment]
@bberenberg Should this use the same Slack configuration for reporting anomalies to Slack, or a separate config (e.g. to log to another channel)?

**Comment by bberenberg** [comment]
Use the same one for now, we can improve later if needed.

**Comment by sdegutis** [comment]
Leaving this open until we deploy and verify, presumably tomorrow morning.

**Comment by bberenberg** [comment]
Not seeing anything from this in Slack thus far, which I find a bit surprising.

**Comment by sdegutis** [comment]
This one's hard to know when to close out, since it runs on "no news is good news". I did a manual test of cloning prod data locally, deleting some of it, and running it locally, and it definitely reported the right errors into Slack. So it seems to work.

**Comment by bberenberg** [comment]
Closing for now.
