### ISSUE TITLE
Flag deals transacted by partner

### ISSUE THREAD

**Issue by bberenberg** [Atlas-Authority/marketing-automation#61]
I don't think we currently track this in any way do we?

Is there a property type where we can create a link to a company so it's saying something like Partner = Adaptavist and can be referenced? Looks like it's in Beta? https://community.hubspot.com/t5/HubSpot-Community-Blog/HubSpot-Associations-New-and-Improved/ba-p/498908

**Comment by sdegutis** [comment]
Putting findings here so it's easier to find:

### Is this ready yet?

Not really.

1. Their SDK doesn't support this yet
2. Opting in is a one-way trip
3. It's still in beta and relatively new

When it's out of beta and the SDK is ready, I think it'll be ready to look into again.

### Can we get around it now?

Yep.

1. Make a new field on Deals: "Partner-transacted" type=checkbox (boolean)
2. Set this to true when any tech/billing contact is a partner? **(Note: this logic needs verification)**
3. Use this new field as a filter on deals in web UI as needed

**Comment by bberenberg** [comment]
So I am thinking we would want to add a flag to deals based on a partner contact on a transaction, or a known partner domain as a billing/tech contact.

Also, tag on a customer if we see a deal that matches this?

**Comment by sdegutis** [comment]
So basically:

1. If a deal is based on a monetary transaction
2. And that monetary transaction has a partner as tech or billing contact
3. Then flag the deal as partner-transaction?

Where "monetary transaction" would mean:

1. A license with license-type "commercial"
2. A transaction with sale-type "new" or "upgrade" or "renewal"

This is the logic the engine uses when deciding to close a deal as "won", so I assume it's the same we want here.

**Comment by bberenberg** [comment]
No this isn't correct.

2. If a deal is based on a monetary transaction
3. And that monetary transaction has a partner as partner contact
4. Then flag the deal as partner-transaction

If a contact is associated with a partner-transaction deal then flag contact as being partner-managed

Also, it may be better to use partner domain instead of a checkbox. That way we can group / filter / etc in the future? Also if a customer switches partners we will know?

**Comment by sdegutis** [comment]
> No this isn't correct.
> 
> 2. If a deal is based on a monetary transaction
> 3. And that monetary transaction has a partner as partner contact
> 4. Then flag the deal as partner-transaction

👍 

> If a contact is associated with a partner-transaction deal then flag contact as being partner-managed

👍 

> Also, it may be better to use partner domain instead of a checkbox. That way we can group / filter / etc in the future? Also if a customer switches partners we will know?

That works better, yeah.

**Comment by bberenberg** [comment]
So what do you need from me here? A property on each object type?

**Comment by sdegutis** [comment]
Yep, one for Contact and one for Deal. Just need their internal names. They're both going to be one-line text fields, right?

**Comment by bberenberg** [comment]
Is there a better option?

**Comment by sdegutis** [comment]
Not that I know of.

**Comment by bberenberg** [comment]
For contacts "last_associated_partner" - defaults empty, the domain of the most recent partner we see associated with them should be set. If the most recent transaction had no partner, clear the field.

**Comment by bberenberg** [comment]
Derp, did a typo with properties, should be `associated_partner` for Deals.

I assume that there aren't partners selling to partners, but I can image some stupid scenario, in which case prioritize the Partner contact above others.

**Comment by sdegutis** [comment]
Ok that makes sense. So in the end, the logic for deal's `associated_partner` would be:

- For each Deal
  - Given all the associated Licenses and Transactions
    - Find the first partner contact, by checking these in order:
      - All Partner contacts first
      - All Billing contacts next
      - All Tech contacts last
  - As soon as we find one that's a partner:
    - Set deal's `associated_partner` to the partner domain
  - But if none are partner:
    - Make `associated_partner` be empty

**Comment by bberenberg** [comment]
Yup

**Comment by sdegutis** [comment]
I think that edge-case needs us to check if there's a partner in the Partner contact *and* one of the Billing or Tech contacts in the same transaction. Otherwise the Partner contact is always going to be a partner-type.

**Comment by sdegutis** [comment]
> For contacts "last_associated_partner" - defaults empty, the domain of the most recent partner we see associated with them should be set. If the most recent transaction had no partner, clear the field.

Who do we set this on? I assume all Customer contacts in the same latest-transaction where we find a Partner transaction? Or do we go further and set it on *all* Customer contacts associated with a Deal that we just set `associated_partner` on (in the above flowchart)?

**Comment by bberenberg** [comment]
`I think that edge-case needs us to check if there's a partner in the Partner contact and one of the Billing or Tech contacts in the same transaction. Otherwise the Partner contact is always going to be a partner-type.`

not sure what you mean, thats exactly what we want, priority in the order I wrote.

**Comment by sdegutis** [comment]
> For contacts `last_associated_partner` - defaults empty, the domain of the most recent partner we see associated with them should be set. If the most recent transaction had no partner, clear the field.
> 
> For deals `associated_partner`, fill with domain if associated transaction has a partner in any user field, not only partner contact.

Got some clarification on this.

Basically, if any records in a deal were associated with a partner, then it's always going to be considered a partner deal. That's why we want "Associated Partner" and not "*Last* Associated Partner".

Whereas, with a contact, they might switch partners, and they might switch to *no* partner. So we want to know who was their most recent partner according to their latest known transaction history.

And domain in this case seems the best way of identifying partner. We probably should lowercase it (if we don't already) and I think that's the only normalization we'll need. (Maybe deal with unicode?)

Also, putting this note here: We may want to do this at the Company level as well, not just Contact.
