### ISSUE TITLE
Handle Duplicate Deals

### ISSUE THREAD

**Issue by sdegutis** [Atlas-Authority/marketing-automation#68]
_Originally posted by @bberenberg in https://github.com/Atlas-Authority/marketing-automation/issues/24#issuecomment-973115895_

My idea would be to have an option controlled by two ENV variable. One for how do you handle duplicate issues. The other for how you handle deletions in general.

Name HUBSPOT_DUPLICATE
Options are:

- none
- log (default)
- delete

Options are comma separated and can be stacked. If none is combined with others, then it's a noop and overrides the other options.

Name: HUBSPOT_DELETE

Options are:
- none - prevent deletions
- log (default)  - log intended deletions
- delete - perform the actual deletion
- slack - notify slack of an intended deletion

Options are comma separated and can be stacked. If none is combined with others, then it's a noop and overrides the other options.

Intent here is that we would roll this out with only `log,slack` initially, see what comes up, then if it's sane, we can enable the delete flag and have something like `log,slack,delete`. We can also enable the delete flag for a single restart when we want to run a cleanup of some kind of data.

_Originally posted by @bberenberg in https://github.com/Atlas-Authority/marketing-automation/issues/24#issuecomment-973115895_

**Comment by sdegutis** [comment]
*(Copying over my [two](https://github.com/Atlas-Authority/marketing-automation/issues/24#issuecomment-1002661970) [comments](https://github.com/Atlas-Authority/marketing-automation/issues/24#issuecomment-1002662670) from that issue.)*

This sounds like a good idea, but I wonder about the fact that it has the same options duplicated between the two actions, just at different levels. I think we could probably combine them, since the only time we'll probably ever want to delete any HS data is when it's a closed-lost and $0 duplicate deal. I can't imagine any other time we'd want to delete.

Also, I think this might be a good use-case for a web UI. So that the web UI can show the most recent run's result data, making it filterable, searchable, etc. and also providing buttons for various actions. The only ones right now would be to delete duplicate deals.

**Comment by bberenberg** [comment]
They're not duplicate options. One is a failsafe on all deletions. One is a specific scenario handler. I would prefer to avoid a webui because then we're managing even more stuff like auth and security.

**Comment by sdegutis** [comment]
### Why do we sometimes see dups disappear over time?

I goofed in designing the deal lookup, not taking into account that there might be dups. It uses an index where "last one wins" if there are multiple deals using the same MPAC record's ID.

Finding all deals by MPAC ID, and then reducing them down to one deal, are intentionally two separate steps. But in the first step, I accidentally reduce them down to one *in some cases*.

### What do we do to fix this?

Update the deal lookup by MPAC IDs to find *all* deals that match.

In other words, combine the two steps described above.

### Super technical notes

First engine run -- before we see dups:

* We don't consider L1 and L2 to be a match
* We create deal D1 for L1, and D2 for L2

Second engine run -- after engine rules changed or bugs fixed:

* We now match up L1 and L2 together
* We find deals D1 and D2 for them
* We log D2 as a dup and ignore it
* We update D1 to point to L2 which is the newer license

Quick note about L1 at this point:

* Future runs won't care about L1
  * Because it's in the same match group as L2
  * And if we find a deal for L2, we don't create one for L1

Third engine run:

* In preparation for deal-lookups, we index deals by License ID:
  * Both D2 and D1 have L2 as their license
  * The engine sets them in an undefined order
  * This actually happened, in this order:
    * Lookup for L2 = D2
    * Lookup for L2 = D1

So what happened here?

* When we looked up L2, we only found D1
  * This is because lookup index uses "last won wins"
  * Therefore D2 isn't even *seen*, and we never log it as a dup

**Comment by sdegutis** [comment]
Oh! Here's an idea that makes this easier: why don't we just add a flag "Is Duplicate" (checkbox/boolean) in HubSpot, and set this via MAE? Then you can filter/inspect/export dups via HS, and even delete them from there.

**Comment by bberenberg** [comment]
Sure I guess, but this still doesn't really solve for the validation side of things which is what logging was for. We need a way to compare deals and ensure they're actual dupes until we can trust the automated detection in the code.

**Comment by sdegutis** [comment]
I think the automatic deal detection is now very solid and thorough:

1. MAE groups licenses/transactions via similarity-scoring sub-engine
2. For each group, we find every deal for _every_ combination of its license & transaction ids
3. There should only be 1 deal; if there are any more, it's definitely a dup

Besides that, we now have really thorough local testing code, like running the engine 3x on the same inputs, which has been catching dup-creating bugs during the dev phase successfully for over a month.

And after the new data shift (#59) task, we'll be able to update the run-3x dev task so that it runs on *different* inputs over time, which will make this even more thorough.

This means dup-creating-bugs should usually be caught at the dev phase now. Which means dups will be rare (maybe 100/year?) and we just have to batch-delete them occasionally.

In which case, the easiest solution to this issue (handle dup deals) is just to mark them in HS to make them easier to manually spot-check (which at this point is a triple-check) & delete.

**Comment by sdegutis** [comment]
Oh, the other benefit of marking them in HS is that, before we delete them, they won't be manually acted on (sending the customer an email, etc) because the person in HS will see they're dups --- or they can be filtered out of the view in HS before acting on deals, etc.

**Comment by sdegutis** [comment]
- [ ] Add new optional field "Duplicate Of"
- [ ] When downloading HubSpot deals, ignore ones with "Duplicate Of" set (they're duplicates)
- [ ] When finding a duplicate, set this field to the ID of the primary deal -- or should it be a link to the deal?

**Comment by bberenberg** [comment]
Why ignore dupes when downloading? Wouldn't that break the dupe finder / mapper?

**Comment by sdegutis** [comment]
Nope. After it flags them as dupes, the next engine run doesn't need to re-flag them, they're already known as dups, and there's nothing to do with them anymore, they just need to be deleted at this point.
