### ISSUE TITLE
Fix summary reporting inconsistencies

### ISSUE THREAD

**Issue by sdegutis** [Atlas-Authority/marketing-automation#70]
The summary report might sometimes double-account for transactions, showing an over-accounting in the final balance.

**Comment by bberenberg** [comment]
Again I don't think we actually want to zero it out. We still earned the money, same goes for stage. We can filter based on the various partner fields on contacts and deals. 

@sdegutis why did you think we needed this?

**Comment by sdegutis** [comment]
Right, I wrote this before our conversation about this yesterday.

**Comment by bberenberg** [comment]
Should we close this out?

**Comment by sdegutis** [comment]
Not yet, I still need to fix some summary reporting, which is what this issue originally was. I'll update the title/desc.
